amb-agent:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  command:
  - systemd.setenv=USE_CONSUL_DNS=false
  - systemd.setenv=AMBARI_SERVER_ADDR=amb-server
  - systemd.setenv=CLOUD_PLATFORM=RANCHER
#  - systemd.setenv=CONSUL_DNS_IP=${consul_dns_ip}
  image: cloudchchen/ambari-agent:latest
  privileged: true
  dns_search:
  - node.dc1.consul
  dns:
  - consul-dns
amb-server:
  ports:
  - 8080:8080/tcp
  labels:
    io.rancher.container.pull_image: always
  command:
  - systemd.setenv=USE_CONSUL_DNS=false
  - systemd.setenv=CLOUD_PLATFORM=RANCHER
#  - systemd.setenv=CONSUL_DNS_IP=${consul_dns_ip}
  image: cloudchchen/ambari-server:latest
  privileged: true
  dns_search:
  - node.dc1.consul
  dns:
  - consul-dns
consul-dns:
  labels:
    io.rancher.container.pull_image: always
  command:
  - -server
  - -bootstrap
  image: sequenceiq/consul:v0.5.0-v6
provision:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
  tty: true
  entrypoint:
  - /bin/bash
  image: hortonworks/ambari-server
  links:
  - amb-server:ambariserver
  stdin_open: true
  environment:
    EXPECTED_HOST_COUNT: ${node_count}
    BLUEPRINT: ${blueprint}
